/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author Maulidito
 */
public class Admin_Transaksi extends javax.swing.JFrame {

    /**
     * Creates new form Admin_Transaksi
     */
    public Admin_Transaksi() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        JTTransaksi = new javax.swing.JTable();
        jBKembali = new javax.swing.JButton();
        searchKode = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jCPegawai = new javax.swing.JComboBox<>();
        jBCreate = new javax.swing.JButton();
        jBUpdate = new javax.swing.JButton();
        jBDelete = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jBSiap = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Berlin Sans FB", 0, 36)); // NOI18N
        jLabel1.setText("TRANSAKSI");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(289, 13, -1, -1));

        JTTransaksi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Kode Laundry", "Nama Pegawai", "Nama Customer", "Sepatu (pasang)", "Baju (kg)", "Harga", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(JTTransaksi);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 96, 730, 230));

        jBKembali.setText("Kembali");
        jBKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBKembaliActionPerformed(evt);
            }
        });
        getContentPane().add(jBKembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 60, -1, -1));
        getContentPane().add(searchKode, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, 70, -1));

        jLabel2.setText("Find Kode Laundry :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));
        getContentPane().add(jCPegawai, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, 99, -1));

        jBCreate.setText("Create Transaksi");
        getContentPane().add(jBCreate, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 350, -1, -1));

        jBUpdate.setText("Update Transaksi");
        getContentPane().add(jBUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 350, -1, -1));

        jBDelete.setText("Delete Transksi");
        getContentPane().add(jBDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 350, -1, -1));

        jLabel3.setText("Pegawai");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, -1, -1));

        jBSiap.setText("Siap");
        jBSiap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSiapActionPerformed(evt);
            }
        });
        getContentPane().add(jBSiap, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 350, 112, -1));

        jPanel1.setLayout(null);

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jPanel2);
        jPanel2.setBounds(0, 0, 750, 410);

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\ASUS\\Desktop\\pic\\LAUNDROMATTTT.jpg")); // NOI18N
        jPanel1.add(jLabel5);
        jLabel5.setBounds(0, 0, 750, 410);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, 410));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBKembaliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBKembaliActionPerformed

    private void jBSiapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSiapActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBSiapActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin_Transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin_Transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin_Transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin_Transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admin_Transaksi().setVisible(true);
            }
        });
    }

    public JTable getJTTransaksi() {
        return JTTransaksi;
    }

    public JButton getjBCreate() {
        return jBCreate;
    }

    public JButton getjBDelete() {
        return jBDelete;
    }

    public JButton getjBKembali() {
        return jBKembali;
    }

    public JButton getjBTransaksi() {
        return jBUpdate;
    }

    public JComboBox<String> getjCPegawai() {
        return jCPegawai;
    }

    public JTextField getSearchKode() {
        return searchKode;
    }

    public void setJTTransaksi(JTable JTTransaksi) {
        this.JTTransaksi = JTTransaksi;
    }

    public void setjCPegawai(String jCPegawai) {
        this.jCPegawai.addItem(jCPegawai);
    }

    public JButton getjBUpdate() {
        return jBUpdate;
    }

    public void setjBUpdate(JButton jBUpdate) {
        this.jBUpdate = jBUpdate;
    }

    public JButton getjBSiap() {
        return jBSiap;
    }
    
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable JTTransaksi;
    private javax.swing.JButton jBCreate;
    private javax.swing.JButton jBDelete;
    private javax.swing.JButton jBKembali;
    private javax.swing.JButton jBSiap;
    private javax.swing.JButton jBUpdate;
    private javax.swing.JComboBox<String> jCPegawai;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField searchKode;
    // End of variables declaration//GEN-END:variables

public void addActionListener(ActionListener e){
    jBCreate.addActionListener(e);
    jBDelete.addActionListener(e);
    jBKembali.addActionListener(e);
    jBUpdate.addActionListener(e);
    jBSiap.addActionListener(e);


}
}
