package View;


import java.awt.TextField;
import java.awt.event.ActionListener;
import javax.swing.ButtonGroup;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JRadioButton;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ASUS
 */
public class Pakaian extends javax.swing.JFrame {

    /**
     * Creates new form GUI
     */
    public Pakaian() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu3 = new javax.swing.JMenu();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu4 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jDialog1 = new javax.swing.JDialog();
        jMenu1 = new javax.swing.JMenu();
        buttonGroup1 = new javax.swing.ButtonGroup();
        hargaPakaian = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        tabelnama = new java.awt.Label();
        jCCustomer = new javax.swing.JComboBox<>();
        jCPegawai = new javax.swing.JComboBox<>();
        jlabel1 = new java.awt.Label();
        JTPakaian = new java.awt.TextField();
        label2 = new java.awt.Label();
        jLabel2 = new javax.swing.JLabel();
        JTSepatu = new java.awt.TextField();
        jLabel3 = new javax.swing.JLabel();
        Hitung = new javax.swing.JButton();
        Proses = new javax.swing.JButton();
        Kembali = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jRSiap = new javax.swing.JRadioButton();
        jRProses = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jLTransaksi = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        jMenu3.setText("jMenu3");

        jMenu4.setText("File");
        jMenuBar2.add(jMenu4);

        jMenu5.setText("Edit");
        jMenuBar2.add(jMenu5);

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(250, 0, 0));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setPreferredSize(new java.awt.Dimension(700, 412));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        hargaPakaian.setBackground(new java.awt.Color(0, 0, 0));
        hargaPakaian.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        hargaPakaian.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        hargaPakaian.setName(""); // NOI18N
        getContentPane().add(hargaPakaian, new org.netbeans.lib.awtextra.AbsoluteConstraints(261, 312, 105, 30));

        jPanel1.setLayout(null);
        jPanel1.add(jLabel5);
        jLabel5.setBounds(0, 0, 0, 0);

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tabelnama.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tabelnama.setText("Nama Customer :");
        jPanel2.add(tabelnama, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, -1, 37));

        jCCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCCustomerActionPerformed(evt);
            }
        });
        jPanel2.add(jCCustomer, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 150, 207, -1));

        jPanel2.add(jCPegawai, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 140, 174, 37));

        jlabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jlabel1.setText("Pakaian :");
        jPanel2.add(jlabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 190, -1, 30));

        JTPakaian.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        JTPakaian.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        JTPakaian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTPakaianActionPerformed(evt);
            }
        });
        JTPakaian.addTextListener(new java.awt.event.TextListener() {
            public void textValueChanged(java.awt.event.TextEvent evt) {
                JTPakaianTextValueChanged(evt);
            }
        });
        jPanel2.add(JTPakaian, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 190, 87, 33));

        label2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        label2.setText(".kg");
        jPanel2.add(label2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 190, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setText("Sepatu :");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 240, -1, -1));

        JTSepatu.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        JTSepatu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTSepatuActionPerformed(evt);
            }
        });
        JTSepatu.addTextListener(new java.awt.event.TextListener() {
            public void textValueChanged(java.awt.event.TextEvent evt) {
                JTSepatuTextValueChanged(evt);
            }
        });
        jPanel2.add(JTSepatu, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 240, 87, 33));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel3.setText("pasang");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 240, -1, -1));

        Hitung.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Hitung.setText("Hitung!");
        Hitung.setPreferredSize(new java.awt.Dimension(100, 150));
        Hitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HitungActionPerformed(evt);
            }
        });
        jPanel2.add(Hitung, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 300, 87, 30));

        Proses.setText("Proses");
        Proses.setEnabled(false);
        jPanel2.add(Proses, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 340, -1, -1));

        Kembali.setText("Kembali");
        jPanel2.add(Kembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 340, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Rp.");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 300, -1, 30));

        buttonGroup1.add(jRSiap);
        jRSiap.setSelected(true);
        jRSiap.setText("Siap");
        jPanel2.add(jRSiap, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 250, -1, -1));

        buttonGroup1.add(jRProses);
        jRProses.setText("Proses");
        jPanel2.add(jRProses, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 250, -1, -1));

        jLabel1.setFont(new java.awt.Font("Berlin Sans FB", 0, 36)); // NOI18N
        jLabel1.setText("LAUNDRY NYA BERAPAAN?");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel1.setPreferredSize(new java.awt.Dimension(500, 100));
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 0, 450, 38));

        jLTransaksi.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.add(jLTransaksi, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 598, 37));

        jPanel1.add(jPanel2);
        jPanel2.setBounds(10, 10, 680, 380);

        jLabel6.setIcon(new javax.swing.ImageIcon("C:\\Users\\ASUS\\Desktop\\pic\\LAUNDROMATTTT.jpg")); // NOI18N
        jPanel1.add(jLabel6);
        jLabel6.setBounds(0, 0, 700, 410);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 410));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JTPakaianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTPakaianActionPerformed

    }//GEN-LAST:event_JTPakaianActionPerformed

    private void HitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HitungActionPerformed
        // TODO add your handling code here:
 
    }//GEN-LAST:event_HitungActionPerformed

    private void JTPakaianTextValueChanged(java.awt.event.TextEvent evt) {//GEN-FIRST:event_JTPakaianTextValueChanged
        // TODO add your handling code here
    }//GEN-LAST:event_JTPakaianTextValueChanged

    private void JTSepatuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTSepatuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTSepatuActionPerformed

    private void JTSepatuTextValueChanged(java.awt.event.TextEvent evt) {//GEN-FIRST:event_JTSepatuTextValueChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_JTSepatuTextValueChanged

    private void jCCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCCustomerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCCustomerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pakaian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pakaian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pakaian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pakaian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Pakaian().setVisible(true);
            
        });
    }

    public String getJTPakaian() {
        return JTPakaian.getText();
    }

    public void setJTPakaian(String JTPakaian) {
        this.JTPakaian.setText(JTPakaian);
    }

    public String getJTSepatu() {
        return JTSepatu.getText();
    }

    public void setJTSepatu(String JTSepatu) {
        this.JTSepatu.setText(JTSepatu);
    }
    

    public JButton getProses() {
        return Proses;
    }
    

    public JButton getHitung() {
        return Hitung;
    }

    public void setHitung(JButton Hitung) {
        this.Hitung = Hitung;
    }

    public String getPakaian() {
        return JTPakaian.getText();
    }

    public void setPakaian(TextField pakaian) {
        this.JTPakaian = pakaian;
    }

    public String getSepatu() {
        return JTSepatu.getText();
    }

    public void setSepatu(TextField sepatu) {
        this.JTSepatu = sepatu;
    }

    public JComboBox<String> getjCCustomer() {
        return jCCustomer;
    }

    public void setjCCustomer(String jCCustomer) {
        this.jCCustomer.addItem(jCCustomer);
    }

    public String getHargaPakaian() {
        return hargaPakaian.getText();
    }

    public void setHargaPakaian(String hargaPakaian) {
        this.hargaPakaian.setText(hargaPakaian);
    }

    public JLabel getjLTransaksi() {
        return jLTransaksi;
    }

    public void setjLTransaksi(String jLTransaksi) {
        this.jLTransaksi.setText(jLTransaksi);
    }

    public JComboBox<String> getjCPegawai() {
        return jCPegawai;
    }

    public void setjCPegawai(String jCPegawai) {
        this.jCPegawai.addItem(jCPegawai);
    }

    public JButton getKembali() {
        return Kembali;
    }

    public String getButtonGroup1() {
        if (getjRSiap().isSelected()){
            return "Siap";
        }else{
            return "Proses";
        }
    }

    public void setButtonGroup1(ButtonGroup buttonGroup1) {
        this.buttonGroup1 = buttonGroup1;
    }

    public JRadioButton getjRProses() {
        return jRProses;
    }

    public void setjRProses(JRadioButton jRProses) {
        this.jRProses = jRProses;
    }

    public JRadioButton getjRSiap() {
        return jRSiap;
    }

    public void setjRSiap(JRadioButton jRSiap) {
        this.jRSiap = jRSiap;
    }
    
    
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Hitung;
    private java.awt.TextField JTPakaian;
    private java.awt.TextField JTSepatu;
    private javax.swing.JButton Kembali;
    private javax.swing.JButton Proses;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel hargaPakaian;
    private javax.swing.JComboBox<String> jCCustomer;
    private javax.swing.JComboBox<String> jCPegawai;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLTransaksi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton jRProses;
    private javax.swing.JRadioButton jRSiap;
    private java.awt.Label jlabel1;
    private java.awt.Label label2;
    private java.awt.Label tabelnama;
    // End of variables declaration//GEN-END:variables

    
    public void addActionListener(ActionListener e){
        Hitung.addActionListener(e);
        Proses.addActionListener(e);
        Kembali.addActionListener(e);
    }
}
