package View;


import java.awt.TextField;
import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ASUS
 */
public class Pakaian extends javax.swing.JFrame {

    /**
     * Creates new form GUI
     */
    public Pakaian() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu3 = new javax.swing.JMenu();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu4 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jDialog1 = new javax.swing.JDialog();
        jMenu1 = new javax.swing.JMenu();
        jLabel1 = new javax.swing.JLabel();
        JTPakaian = new java.awt.TextField();
        jlabel1 = new java.awt.Label();
        label2 = new java.awt.Label();
        Hitung = new javax.swing.JButton();
        hargaPakaian = new javax.swing.JLabel();
        tabelnama = new java.awt.Label();
        jLabel2 = new javax.swing.JLabel();
        JTSepatu = new java.awt.TextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Proses = new javax.swing.JButton();
        Kembali = new javax.swing.JButton();
        jCCustomer = new javax.swing.JComboBox<>();
        jLTransaksi = new javax.swing.JLabel();
        jCPegawai = new javax.swing.JComboBox<>();

        jMenu3.setText("jMenu3");

        jMenu4.setText("File");
        jMenuBar2.add(jMenu4);

        jMenu5.setText("Edit");
        jMenuBar2.add(jMenu5);

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(250, 0, 0));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setPreferredSize(new java.awt.Dimension(500, 300));

        jLabel1.setFont(new java.awt.Font("Berlin Sans FB", 0, 48)); // NOI18N
        jLabel1.setText("LAUNDRY NYA BERAPAAN?");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel1.setPreferredSize(new java.awt.Dimension(500, 100));

        JTPakaian.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        JTPakaian.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        JTPakaian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTPakaianActionPerformed(evt);
            }
        });
        JTPakaian.addTextListener(new java.awt.event.TextListener() {
            public void textValueChanged(java.awt.event.TextEvent evt) {
                JTPakaianTextValueChanged(evt);
            }
        });

        jlabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jlabel1.setText("Pakaian :");

        label2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        label2.setText(".kg");

        Hitung.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Hitung.setText("Hitung!");
        Hitung.setPreferredSize(new java.awt.Dimension(100, 150));
        Hitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HitungActionPerformed(evt);
            }
        });

        hargaPakaian.setBackground(new java.awt.Color(0, 0, 0));
        hargaPakaian.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        hargaPakaian.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        hargaPakaian.setName(""); // NOI18N

        tabelnama.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        tabelnama.setText("Nama Customer :");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setText("Sepatu :");

        JTSepatu.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        JTSepatu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTSepatuActionPerformed(evt);
            }
        });
        JTSepatu.addTextListener(new java.awt.event.TextListener() {
            public void textValueChanged(java.awt.event.TextEvent evt) {
                JTSepatuTextValueChanged(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel3.setText("pasang");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Rp.");

        Proses.setText("Proses");
        Proses.setEnabled(false);

        Kembali.setText("Kembali");

        jCCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCCustomerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jlabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(JTSepatu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(JTPakaian, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(Hitung, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(Kembali)
                                .addGap(18, 18, 18)
                                .addComponent(Proses))
                            .addComponent(tabelnama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(hargaPakaian, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel3)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addComponent(jCCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(59, 59, 59)
                                .addComponent(jCPegawai, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, 598, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addComponent(jLTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jCCustomer)
                        .addComponent(jCPegawai, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(tabelnama, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JTPakaian, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(78, 78, 78))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel2)
                                .addComponent(JTSepatu, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel3))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(hargaPakaian, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Hitung, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Proses)
                                    .addComponent(Kembali))))
                        .addGap(46, 46, 46))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JTPakaianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTPakaianActionPerformed

    }//GEN-LAST:event_JTPakaianActionPerformed

    private void HitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HitungActionPerformed
        // TODO add your handling code here:
 
    }//GEN-LAST:event_HitungActionPerformed

    private void JTPakaianTextValueChanged(java.awt.event.TextEvent evt) {//GEN-FIRST:event_JTPakaianTextValueChanged
        // TODO add your handling code here
    }//GEN-LAST:event_JTPakaianTextValueChanged

    private void JTSepatuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTSepatuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTSepatuActionPerformed

    private void JTSepatuTextValueChanged(java.awt.event.TextEvent evt) {//GEN-FIRST:event_JTSepatuTextValueChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_JTSepatuTextValueChanged

    private void jCCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCCustomerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCCustomerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pakaian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pakaian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pakaian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pakaian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Pakaian().setVisible(true);
            
        });
    }

    public String getJTPakaian() {
        return JTPakaian.getText();
    }

    public void setJTPakaian(String JTPakaian) {
        this.JTPakaian.setText(JTPakaian);
    }

    public String getJTSepatu() {
        return JTSepatu.getText();
    }

    public void setJTSepatu(String JTSepatu) {
        this.JTSepatu.setText(JTSepatu);
    }
    

    public JButton getProses() {
        return Proses;
    }
    

    public JButton getHitung() {
        return Hitung;
    }

    public void setHitung(JButton Hitung) {
        this.Hitung = Hitung;
    }

    public String getPakaian() {
        return JTPakaian.getText();
    }

    public void setPakaian(TextField pakaian) {
        this.JTPakaian = pakaian;
    }

    public String getSepatu() {
        return JTSepatu.getText();
    }

    public void setSepatu(TextField sepatu) {
        this.JTSepatu = sepatu;
    }

    public JComboBox<String> getjCCustomer() {
        return jCCustomer;
    }

    public void setjCCustomer(String jCCustomer) {
        this.jCCustomer.addItem(jCCustomer);
    }

    public String getHargaPakaian() {
        return hargaPakaian.getText();
    }

    public void setHargaPakaian(String hargaPakaian) {
        this.hargaPakaian.setText(hargaPakaian);
    }

    public JLabel getjLTransaksi() {
        return jLTransaksi;
    }

    public void setjLTransaksi(String jLTransaksi) {
        this.jLTransaksi.setText(jLTransaksi);
    }

    public JComboBox<String> getjCPegawai() {
        return jCPegawai;
    }

    public void setjCPegawai(String jCPegawai) {
        this.jCPegawai.addItem(jCPegawai);
    }

    public JButton getKembali() {
        return Kembali;
    }
    
    
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Hitung;
    private java.awt.TextField JTPakaian;
    private java.awt.TextField JTSepatu;
    private javax.swing.JButton Kembali;
    private javax.swing.JButton Proses;
    private javax.swing.JLabel hargaPakaian;
    private javax.swing.JComboBox<String> jCCustomer;
    private javax.swing.JComboBox<String> jCPegawai;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLTransaksi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar2;
    private java.awt.Label jlabel1;
    private java.awt.Label label2;
    private java.awt.Label tabelnama;
    // End of variables declaration//GEN-END:variables

    
    public void addActionListener(ActionListener e){
        Hitung.addActionListener(e);
        Proses.addActionListener(e);
        Kembali.addActionListener(e);
    }
}
