/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.awt.event.ActionListener;
import javax.swing.ButtonGroup;
import javax.swing.JButton;
import javax.swing.JFormattedTextField;
import javax.swing.JLabel;
import javax.swing.JRadioButton;
import javax.swing.JTextField;
import javax.swing.JTextPane;

/**
 *
 * @author ASUS
 */
public class Registrasi_Customer extends javax.swing.JFrame {

    /**
     * Creates new form Registrasi_Customer
     */
    public Registrasi_Customer() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jFtgl_lahir = new javax.swing.JFormattedTextField();
        jRLaki = new javax.swing.JRadioButton();
        jRPerempuan = new javax.swing.JRadioButton();
        jBDone = new javax.swing.JButton();
        jTNama = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTAlamat = new javax.swing.JTextPane();
        jLIdcustomer = new javax.swing.JLabel();
        jBCancel = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Nama :");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, 69, -1));

        jLabel2.setText("Alamat :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, 69, -1));

        try {
            jFtgl_lahir.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##-##-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFtgl_lahir.setToolTipText("00-00-0000");
        getContentPane().add(jFtgl_lahir, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 200, 157, -1));

        buttonGroup1.add(jRLaki);
        jRLaki.setSelected(true);
        jRLaki.setText("LAKI");
        getContentPane().add(jRLaki, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 240, -1, -1));

        buttonGroup1.add(jRPerempuan);
        jRPerempuan.setText("PEREMPUAN");
        getContentPane().add(jRPerempuan, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 240, -1, -1));

        jBDone.setText("Done");
        getContentPane().add(jBDone, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 290, -1, -1));

        jTNama.setToolTipText("sebagai Username");
        jTNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTNamaActionPerformed(evt);
            }
        });
        getContentPane().add(jTNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 60, 294, -1));

        jLabel3.setText("Tanggal Lahir :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 200, -1, -1));

        jScrollPane1.setViewportView(jTAlamat);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 110, 294, 62));
        getContentPane().add(jLIdcustomer, new org.netbeans.lib.awtextra.AbsoluteConstraints(579, 19, 104, 32));

        jBCancel.setText("Cancel");
        getContentPane().add(jBCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 290, -1, -1));

        jPanel1.setLayout(null);

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jPanel2);
        jPanel2.setBounds(30, 30, 650, 300);

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\ASUS\\Desktop\\pic\\LAUNDROMATTTT.jpg")); // NOI18N
        jPanel1.add(jLabel4);
        jLabel4.setBounds(0, 0, 700, 410);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 410));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTNamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTNamaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registrasi_Customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registrasi_Customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registrasi_Customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registrasi_Customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registrasi_Customer().setVisible(true);
            }
        });
    }

    public String getjFtgl_lahir() {
        return jFtgl_lahir.getText();
    }

    public void setjFtgl_lahir(String jFtgl_lahir) {
        this.jFtgl_lahir.setText(jFtgl_lahir);
    }

    public JRadioButton getjRLaki() {
        return jRLaki;
    }

    public void setjRLaki(JRadioButton jRLaki) {
        this.jRLaki = jRLaki;
    }

    public JRadioButton getjRPerempuan() {
        return jRPerempuan;
    }

    public void setjRPerempuan(JRadioButton jRPerempuan) {
        this.jRPerempuan = jRPerempuan;
    }

    public String getjTAlamat() {
        return jTAlamat.getText();
    }

    public void setjTAlamat(String jTAlamat) {
        this.jTAlamat.setText(jTAlamat);
    }

    public String getjTNama() {
        return jTNama.getText();
    }

    public void setjTNama(String jTNama) {
        this.jTNama.setText(jTNama);
    }

    public JButton getjBDone() {
        return jBDone;
    }

    public String getjLIdcustomer() {
        return jLIdcustomer.getText();
    }

    public void setjLIdcustomer(String jLIdcustomer) {
        this.jLIdcustomer.setText(jLIdcustomer);
    }

    public String getButtonGroup1() {
        if (jRLaki.isSelected()){
            return jRLaki.getText();
        }else{
            return jRPerempuan.getText();
        }
    }

    public void setButtonGroup1(ButtonGroup buttonGroup1) {
        this.buttonGroup1 = buttonGroup1;
    }

    public JButton getjBCancel() {
        return jBCancel;
    }
    
    
    

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jBCancel;
    private javax.swing.JButton jBDone;
    private javax.swing.JFormattedTextField jFtgl_lahir;
    private javax.swing.JLabel jLIdcustomer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton jRLaki;
    private javax.swing.JRadioButton jRPerempuan;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextPane jTAlamat;
    private javax.swing.JTextField jTNama;
    // End of variables declaration//GEN-END:variables
   
    public void addActionListener(ActionListener e){
        jBDone.addActionListener(e);
        jBCancel.addActionListener(e);
    
    }

}
