/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.awt.event.ActionListener;
import javax.swing.ButtonGroup;
import javax.swing.JButton;
import javax.swing.JFormattedTextField;
import javax.swing.JLabel;
import javax.swing.JPasswordField;
import javax.swing.JRadioButton;
import javax.swing.JTextField;

/**
 *
 * @author ASUS
 */
public class Registrasi_Pegawai extends javax.swing.JFrame {

    /**
     * Creates new form Registrasi_Pegawai
     */
    public Registrasi_Pegawai() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLIdpeg = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTNama = new javax.swing.JTextField();
        jPpass = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jFtgl_lahir = new javax.swing.JFormattedTextField();
        jRLaki = new javax.swing.JRadioButton();
        jRPerempuan = new javax.swing.JRadioButton();
        jBCancel = new javax.swing.JButton();
        jBDone = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jLIdpeg, new org.netbeans.lib.awtextra.AbsoluteConstraints(534, 25, 141, 36));

        jPanel1.setLayout(null);

        jLabel1.setText("Nama");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(210, 130, 69, 16);

        jTNama.setToolTipText("sebagai Username");
        jPanel1.add(jTNama);
        jTNama.setBounds(350, 130, 157, 22);
        jPanel1.add(jPpass);
        jPpass.setBounds(350, 170, 157, 22);

        jLabel2.setText("Password");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(210, 170, 69, 16);

        jLabel3.setText("Tanggal Lahir");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(210, 210, 78, 16);

        try {
            jFtgl_lahir.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##-##-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFtgl_lahir.setToolTipText("00-00-0000");
        jPanel1.add(jFtgl_lahir);
        jFtgl_lahir.setBounds(350, 210, 157, 22);

        buttonGroup1.add(jRLaki);
        jRLaki.setSelected(true);
        jRLaki.setText("LAKI");
        jPanel1.add(jRLaki);
        jRLaki.setBounds(340, 250, 53, 25);

        buttonGroup1.add(jRPerempuan);
        jRPerempuan.setText("PEREMPUAN");
        jPanel1.add(jRPerempuan);
        jRPerempuan.setBounds(410, 250, 99, 25);

        jBCancel.setText("Cancel");
        jPanel1.add(jBCancel);
        jBCancel.setBounds(440, 280, 71, 25);

        jBDone.setText("Done");
        jPanel1.add(jBDone);
        jBDone.setBounds(370, 280, 61, 25);

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jPanel2);
        jPanel2.setBounds(200, 110, 330, 210);

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\ASUS\\Desktop\\pic\\LAUNDROMATTTT.jpg")); // NOI18N
        jLabel5.setText("jLabel5");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(0, 0, 750, 410);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 410));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public String getButtonGroup1() {
        if (jRLaki.isSelected()){
            return getjRLaki();
        }else{
            return getjRPerempuan();
        }
        
    }
    
    public JButton getjBDone() {
        return jBDone;
    }

    public String getjFtgl_lahir() {
        return jFtgl_lahir.getText();
    }

    public String getjPpass() {
        return jPpass.getText();
    }

    public String getjRLaki() {
        return jRLaki.getText();
    }

    public String getjRPerempuan() {
        return jRPerempuan.getText();
    }

    public void setButtonGroup1(String buttonGroup1) {
         if (buttonGroup1.equals("Laki")){
            jRLaki.setSelected(true);
        }else{
            jRPerempuan.setSelected(true);
        }
    }

    public void setjFtgl_lahir(String jFtgl_lahir) {
        this.jFtgl_lahir.setText(jFtgl_lahir);
    }

    public void setjPpass(String jPpass) {
        this.jPpass.setText(jPpass);
    }

    public void setjRLaki(JRadioButton jRLaki) {
        this.jRLaki = jRLaki;
    }

    public void setjRPerempuan(JRadioButton jRPerempuan) {
        this.jRPerempuan = jRPerempuan;
    }

    public void setjTNama(String jTNama) {
        this.jTNama.setText(jTNama);
    }

    public String getjLIdpeg() {
        return jLIdpeg.getText();
    }

    public void setjLIdpeg(String jLIdpeg) {
        this.jLIdpeg.setText(jLIdpeg);
    }

    public JButton getjBCancel() {
        return jBCancel;
    }

               
    
    
    /**
     * @param args the command line arguments
     */
    public String getjTNama() {
        return jTNama.getText();
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
        * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
        */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registrasi_Pegawai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registrasi_Pegawai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registrasi_Pegawai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registrasi_Pegawai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registrasi_Pegawai().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jBCancel;
    private javax.swing.JButton jBDone;
    private javax.swing.JFormattedTextField jFtgl_lahir;
    private javax.swing.JLabel jLIdpeg;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField jPpass;
    private javax.swing.JRadioButton jRLaki;
    private javax.swing.JRadioButton jRPerempuan;
    private javax.swing.JTextField jTNama;
    // End of variables declaration//GEN-END:variables

public void addActionListener(ActionListener e){
    jBDone.addActionListener(e);
    jBCancel.addActionListener(e);
}
}
